ALTER TABLE CLASSMAP1 DROP FOREIGN KEY classmap1_dono_fk ;
ALTER TABLE CLASSMAP1 DROP FOREIGN KEY classmap1_grupos_fk ;
DROP TABLE CLASSMAP1;

CREATE TABLE CLASSMAP1 (

	ID				integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	NODE			CHAR(30) DEFAULT '',
	PARENT			integer DEFAULT 0,
    SEQ             integer DEFAULT 0,
	TIPO			integer DEFAULT 0,
    CLASSE			char(20) DEFAULT '',
	DTBLK			char(30) DEFAULT '',
	DTBLF			integer DEFAULT 0,
	DONO			integer DEFAULT 0,
	GRUPO			integer DEFAULT 0,
	PERM			integer DEFAULT 436,
	CRIADO			timestamp DEFAULT CURRENT_TIMESTAMP,
	MODIFICADO		timestamp DEFAULT CURRENT_TIMESTAMP,
    KEYWORD			CHAR(60) DEFAULT '',
	COMENT			varchar(256) DEFAULT '',
	FLAG1			integer DEFAULT 0,
	FLAG2			integer DEFAULT 0
);

ALTER TABLE CLASSMAP1 ADD CONSTRAINT classmap1_pk Primary Key (ID);
ALTER TABLE CLASSMAP1 ADD CONSTRAINT classmap1_dono_fk FOREIGN KEY  (DONO) REFERENCES USERS (ID);
ALTER TABLE CLASSMAP1 ADD CONSTRAINT classmap1_grupos_fk FOREIGN KEY (GRUPO) REFERENCES GRUPOS (ID);


insert into classmap1 (NODE,PARENT,TIPO,CLASSE,DTBLK,DTBLF,DONO,GRUPO,PERM,KEYWORD,COMENT,FLAG2) values ('Nivel2',2,1,'ClassNode','',1,2,3,436,'','',87);

CREATE TABLE CANAIS (

	ID                      integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	MASCARA			CHAR(10) DEFAULT '',
	UNIDADE                 CHAR(10) DEFAULT '',
        CANAL			CHAR(2) DEFAULT '00',
	TIPO			CHAR(2) DEFAULT '00',
        A0                      CHAR(10) DEFAULT '0.0',
	A1                      CHAR(10) DEFAULT '0.0',
        A2                      CHAR(10) DEFAULT '0.0',
        A3                      CHAR(10) DEFAULT '0.0',
        A4                      CHAR(10) DEFAULT '0.0',
        A5                      CHAR(10) DEFAULT '0.0',
        ROFFSET                 CHAR(10) DEFAULT '0.0',
        RSLOPE                  CHAR(10) DEFAULT '0.0',
        FLAG1			integer DEFAULT 0,
	FLAG2			integer DEFAULT 0
);

ALTER TABLE CANAIS ADD CONSTRAINT canais_pk Primary Key (ID);
