
ALTER TABLE USERS ADD CONSTRAINT users_pk Primary Key (ID);
ALTER TABLE USERS ADD CONSTRAINT users_fk FOREIGN KEY(GRUPO) REFERENCES GRUPOS (ID);

ALTER TABLE GRUPOS ADD CONSTRAINT grupos_pk Primary Key (ID);

ALTER TABLE CLASSMAP ADD CONSTRAINT classmap_pk Primary Key (ID);
ALTER TABLE CLASSMAP ADD CONSTRAINT classmap_dono_fk FOREIGN KEY  (DONO) REFERENCES USERS (ID);
ALTER TABLE CLASSMAP ADD CONSTRAINT classmap_grupos_fk FOREIGN KEY (GRUPO) REFERENCES GRUPOS (ID);

ALTER TABLE PGNS ADD CONSTRAINT pgns_pk Primary Key (ID);

ALTER TABLE PASSOS ADD CONSTRAINT passos_pk Primary Key (ID);

ALTER TABLE EVENTOS ADD CONSTRAINT eventos_pk Primary Key (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT eventos_fk FOREIGN KEY (PGN) REFERENCES PGNS (ID);

ALTER TABLE IDS ADD CONSTRAINT ids_pk Primary Key (ID);
ALTER TABLE IDS ADD CONSTRAINT ids_evento_fk FOREIGN KEY (EVENTO) REFERENCES EVENTOS (ID);
ALTER TABLE IDS ADD CONSTRAINT ids_cliente_fk FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (ID);

ALTER TABLE CLIENTES ADD CONSTRAINT clientes_pk Primary Key (ID);


