
ALTER TABLE USERS DROP FOREIGN KEY users_fk ;
ALTER TABLE CLASSMAP DROP FOREIGN KEY classmap_dono_fk ;
ALTER TABLE CLASSMAP DROP FOREIGN KEY classmap_grupos_fk ;
ALTER TABLE EVENTOS DROP FOREIGN KEY eventos_fk ;
ALTER TABLE IDS DROP FOREIGN KEY ids_evento_fk ;
ALTER TABLE IDS DROP FOREIGN KEY ids_cliente_fk ;



