/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.opus;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.opus//centauro//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "centauroTopComponent",
        iconBase = "com/opus/atlantik.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "com.opus.centauroTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "Painel Centauro",
        preferredID = "centauroTopComponent")
@Messages({
    "CTL_centauroAction=centauro",
    "CTL_centauroTopComponent=centauro Window",
    "HINT_centauroTopComponent=This is a centauro window"
})
public final class CentauroTopComponent extends TopComponent {

    MonitorTopComponent mtc;
    
    public CentauroTopComponent() {
        initComponents();
        setName("Terminal Jurid (Centauro)");
        //setToolTipText(Bundle.HINT_centauroTopCompon);

    }

    
    public void setMonitor (MonitorTopComponent mtc){
        this.mtc = mtc;
    }
    
    
    public void write (String msg){
        jta1.append(msg);
        jta1.setCaretPosition(jta1.getText().length());
    }
    
    
    public void write (char c){
        jta1.append(String.valueOf(c));
        jta1.setCaretPosition(jta1.getCaretPosition()+1);
    }
    
     private void jta1KeyTyped(java.awt.event.KeyEvent evt) {                              
        // TODO add your handling code here:
        //System.out.println("Key typed :"+ evt.getKeyChar());
        if (mtc != null){
            //mtc.termPutc(evt.getKeyChar());
        }
    }   
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();

        jta1.setEditable(false);
        jta1.setColumns(20);
        jta1.setRows(5);
        jta1.setTabSize(4);
        jScrollPane1.setViewportView(jta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jta1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
